### ISSUE TITLE
Deploy issues with pydata_sphinx_theme in version 0.10.1

### ISSUE THREAD

**Issue by MalteKurz** [DoubleML/doubleml-docs#94]
Currently the sphinx build with pydata_sphinx_theme in version 0.10.1 fails, see https://github.com/DoubleML/doubleml-docs/actions/runs/2991978426. The issue might be related to https://github.com/pydata/pydata-sphinx-theme/issues/911 / https://github.com/pydata/pydata-sphinx-theme/pull/878.
When running `sphinx-build` with increased verbosity, the following exception is thrown
```
Traceback (most recent call last):
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 1048, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/jinja2glue.py", line 188, in render
    return self.environment.get_template(template).render(context)
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html", line 25, in top-level template code
    {% set remove_sidebar_secondary = (meta is defined and meta is not none
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/themes/basic/../basic/layout.html", line 169, in top-level template code
    {%- block content %}
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html", line 75, in block 'content'
    {% block docs_navbar %}
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html", line 77, in block 'docs_navbar'
    {%- include "sections/header.html" %}
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/pydata_sphinx_theme/theme/pydata_sphinx_theme/sections/header.html", line 16, in top-level template code
    {% include navbar_item %}
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/pydata_sphinx_theme/theme/pydata_sphinx_theme/components/navbar-nav.html", line 6, in top-level template code
    {{ generate_header_nav_html(n_links_before_dropdown=theme_header_links_before_dropdown) }}
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/pydata_sphinx_theme/__init__.py", line 250, in generate_header_nav_html
    title = app.env.titles[page].astext()
KeyError: 'self'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 286, in build_update
    self.build(to_build,
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 350, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 524, in write
    self._write_serial(sorted(docnames))
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 534, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 625, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/malte/github_projects/doubleml-docs/venv/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 1055, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page api/api.
Reason: KeyError('self')

Theme error:
An error happened in rendering the page api/api.
Reason: KeyError('self')
```

As an intermediate solution, I try to (temporarily) bump / fix the pydata_sphinx_theme version.

**Comment by MalteKurz** [comment]
Could also be related to one of our templates in https://github.com/DoubleML/doubleml-docs/tree/master/doc/_templates
